
services:
  SqlServerDb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - backend
    volumes:
      - mssqldata:/var/opt/mssql

  gatherly.app:
    container_name: gatherlyapp
    image: ${DOCKER_REGISTRY-}gatherlyapp
    ports : 
    - 5002:80
    - 5003:443
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
    build:
      context: .
      dockerfile: src/Gatherly.App/Dockerfile
    depends_on:
            - SqlServerDb
   
  jaeger:
    image: jaegertracing/jaeger:${JAEGER_VERSION:-latest}
    networks:
      - backend
    ports:
      - "16686:16686"
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
      - "4318:4318"
networks:
  backend:

volumes:
  mssqldata:

